### ISSUE TITLE
echo_location doesn't return the status code 

### ISSUE THREAD

**Issue by grvsaxena419** [openresty/echo-nginx-module#55]
Hi 

If you have a configuration like below 

`location /foo {
    echo_location /bar;
}

location /bar {
    proxy_pass http://some-server
}`

Making a call to /foo always returns 200 instead of returning the status code returned by some-server.

**Comment by agentzh** [comment]
@grvsaxena419 In nginx's design, a subrequest's response status code does not affect its parent request by default. This is understandable since a request can have multiple subrequests and they can carry different status codes. In your example, `echo_location` initiates a subrequest, whose status code won't affect the main request, by definition.
