### ISSUE TITLE
echo around rewrite directive.

### ISSUE THREAD

**Issue by ambjlon** [openresty/echo-nginx-module#63]
```
location = /abc/say {
    echo $document_uri;

    rewrite ^/abc/say$ /xyz/speak last;

    echo $document_uri;
}
```

When the request enter this location, the output is:
**/xyz/speak**
**/xyz/speak**

What I expect is like:
**/abc/say**
**/xyz/speak**

Why?

**Comment by agentzh** [comment]
@ambjlon Because `rewrite` runs in the `rewrite` processing phase while `echo` runs in the `content` phase. In the nginx request processing model, directives run in the `rewrite` phase *always* run *after* those in the `content` phase, no matter how they appear in `nginx.conf`. I suggest you read my nginx tutorials to avoid such beginner mistakes:

http://openresty.org/en/ebooks.html
